password: ENC[AES256_GCM,data:k8xIB30lsmSI,iv:YaJ7WlxZZj9vBQqmZphdYKMzOVFVOuNepCXPOoM1dFI=,tag:C7DI+TGrdRAeuuLhu4+QhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    lastmodified: '2021-09-27T20:43:41Z'
    mac: ENC[AES256_GCM,data:5UkBMJX23x1d58KLT//HW4nIX+Bt4/XIu23eLTuL1lh7y/2MnpvPzAL5wreBfnosSdF7WqFQ/oWkQ6Cscm6ain8dboWh1ZqxRtt5KSX1UxPRMYY5gFeCCKA871bD9HLppF7Zs6s1vw1svrkrjmU8pUHJkODTXw/xNz19B7KZET4=,iv:8KJ9YsuU8Uz8pw3SGMoSWi41PWTwRDOKmE4sL2tWLAw=,tag:sCPl/1tzqodpoi9KQn2r2w==,type:str]
    pgp:
    -   created_at: '2021-09-27T20:42:40Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAxLQDzZ/9zhaAQv/SGl1bnsSUU1HlkvwpcBIE68/Dh5T+8t0dxxlsFlYwGA3
            jkTdNXA04Qd/tLyBC6Xz2wQB24LtxsE+dLFAfXpp9ivfsGjVljIiszbFudT8wnNm
            FoK2CIFKzjd+6j8IuRpVMWEK1rr5wo+oo9KRUIUmbq8mPFxRqb0hON0vTyBUv4hA
            ZWgv0OP5iyZrC56QbRetM3K61+m7V035TFSWDKQnsuNE1QSyWzbMgAMHrWVnZ80c
            VrGaOu5LLy7tz5d7VjguhPFRWFfB0IZgEwBsJtb/amtPPCWNZPDksYvRxLztPe8l
            fgWoKXV9bPTovdrAa6+GxRLe9X4HC67BDCv0a7KhysfQWSieu5GH2O4/lWx2gj/6
            IxPoaS4FUxOlW7zuzFblcwtBRwYu2i5GjBkVPOfsyzM5HY9bKfhI11CwrAoa0XgM
            3yaIyuKvdPcrKVML+6qveMg8qmmjajk+LVy0ectvaESLUE0Og1VPrYKYGwtYyma6
            Dv1fq6JOVBF+xZQzos010l4BkO/HZPuAXJrEBthMOaY/Qe0pog20HxQMUaXheS3K
            rIIPKBCKNcmvKJd4sOZ89/vkP+T6iEBMNZK3guLtuw37yXtX6JvTws2ZpXm/2dWW
            5xppSAas+pMDLMlKs+Cu
            =3uJO
            -----END PGP MESSAGE-----
        fp: 3BC27DA7368C6F2A8C2B443663B20BEE385AB513
    unencrypted_suffix: _unencrypted
    version: 3.0.3
