apiVersion: v1
kind: ConfigMap
metadata:
  name: config.json
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    release: '{{ .Release.Name }}'
    heritage: '{{ .Release.Service }}'
data:
  config.json:
    '{{ .Files.Get "files/config.json" }}'